Separate problem id and name with a dash instead of a dot
In case we wanna compile locally, the following error occors with rustc:

```
❯ rustc 1.two_sum.rs
error: invalid character `.` in crate name: `1.two_sum`

error: aborting due to previous error
```

Fix misleading comments and trailing spaces while at it.